### ISSUE TITLE
"cd *" works but it should not work

### ISSUE THREAD

**Issue by jedeoric** [orix-software/shell#73]

**Comment by Gliou** [comment]
Sur mon ORIX et la version 2022.3 la commande CD / BUG

**Comment by jedeoric** [comment]
oui il y a un bug, le fix est fait depuis un mois, mais je n'avais pas publié le fix car je pensais que personne utilisait le shell :) Je vais publier le fix du coup dès que possible :)

**Comment by jedeoric** [comment]
Done : shell 2023.4
